'use client';

import { useEffect, useState } from 'react';

type PremiumPrefs = { distance: string; budget: string; groupSize: string; availability: string; privateCrew: boolean; recurring: boolean; earlyAccess: boolean; trustedContact: boolean; dateVotes: Record<string, number>; venueVotes: Record<string, number> };
const defaults: PremiumPrefs = { distance: '3 km', budget: 'Free or under $20', groupSize: '2–4 people', availability: 'Friday afternoon', privateCrew: false, recurring: false, earlyAccess: false, trustedContact: false, dateVotes: { 'Friday 4:00 PM': 3, 'Saturday 11:00 AM': 2 }, venueVotes: { 'Courtyard Café': 2, 'Victoria Park': 3 } };
const friendMatches = [{ name: 'Maya', score: 94, reason: 'Free Friday afternoon · likes quiet cafés', avatar: '🌻' },{ name: 'Noah', score: 88, reason: 'Near campus · completed 2 food quests', avatar: '🦊' },{ name: 'Olivia', score: 82, reason: 'Prefers small groups · available weekends', avatar: '🌙' }];
const venues = [{ name: 'Courtyard Café', meta: '8 min walk · $10–20 · quiet', badge: 'BEST MATCH' },{ name: 'Victoria Park', meta: '6 min walk · free · outdoors', badge: 'FREE PICK' },{ name: 'Manning Food Court', meta: '4 min walk · $10–25 · group friendly', badge: 'CLOSEST' }];

export default function PremiumTools({ active, onGetPremium }: { active: boolean; onGetPremium: () => void }) {
  const [prefs, setPrefs] = useState<PremiumPrefs>(defaults);
  const [refreshes, setRefreshes] = useState(2);
  const [saved, setSaved] = useState('');
  useEffect(() => { try { const stored = JSON.parse(window.localStorage.getItem('sidequest-premium-prefs') ?? 'null') as PremiumPrefs | null; if (stored) setPrefs({ ...defaults, ...stored }); } catch { window.localStorage.removeItem('sidequest-premium-prefs'); } }, []);
  const update = (next: PremiumPrefs, message = 'Premium preferences saved.') => { if (!active) return; setPrefs(next); window.localStorage.setItem('sidequest-premium-prefs', JSON.stringify(next)); setSaved(message); };
  const vote = (kind: 'dateVotes' | 'venueVotes', choice: string) => update({ ...prefs, [kind]: { ...prefs[kind], [choice]: prefs[kind][choice] + 1 } }, 'Your vote was added to the crew plan.');

  return <div className={`premium-studio ${active ? 'is-active' : 'is-locked'}`}>
    <header className="premium-studio-head"><div><p className="eyebrow">12 PREMIUM PLANNING TOOLS</p><h2>Find the people, time and place.<br/><em>Skip the planning headache.</em></h2><p>Premium is useful access—not a decorative badge. Every tool helps turn a social intention into a plan that actually happens.</p></div><div className="premium-state"><span>{active ? '✦ PREMIUM ACTIVE' : '◇ PREMIUM PREVIEW'}</span><b>{active ? 'All 12 tools unlocked' : 'Explore what your points unlock'}</b>{!active && <button onClick={onGetPremium}>Get Premium access →</button>}</div></header>
    {saved && <div className="premium-saved" role="status">✓ {saved}<button onClick={() => setSaved('')}>×</button></div>}
    <div className="premium-tool-grid">
      <article className="premium-tool wide"><ToolHead number="01" icon="◎" title="Smart friend matching" text="Find the best people for a Quest using shared interests and availability."/><div className="match-list">{friendMatches.map(friend => <button disabled={!active} key={friend.name} onClick={() => setSaved(`${friend.name} was added to your draft crew.`)}><span>{friend.avatar}</span><p><b>{friend.name}</b><small>{friend.reason}</small></p><strong>{friend.score}%</strong></button>)}</div></article>
      <article className="premium-tool"><ToolHead number="02" icon="◷" title="Common free time" text="Compare free/busy windows without exposing private calendar details."/><div className="time-picks">{['Friday · 3:30–5:00 PM','Saturday · 11:00 AM–1:00 PM'].map((time,index) => <button disabled={!active} key={time} onClick={() => setSaved(`${time} selected for your crew.`)}><b>{index === 0 ? '3 / 3' : '2 / 3'} free</b><span>{time}</span></button>)}</div></article>
      <article className="premium-tool"><ToolHead number="03" icon="⌖" title="Smart venues" text="Recommend safe public places using distance, cost, hours and group size."/><div className="venue-picks">{venues.map(venue => <button disabled={!active} key={venue.name} onClick={() => setSaved(`${venue.name} added to your plan.`)}><small>{venue.badge}</small><b>{venue.name}</b><span>{venue.meta}</span></button>)}</div></article>
      <article className="premium-tool wide"><ToolHead number="04" icon="≡" title="Advanced event filters" text="Build a precise event search around the crew’s real needs."/><div className="premium-filters"><Select label="Distance" disabled={!active} value={prefs.distance} values={['1 km','3 km','5 km','Anywhere in Sydney']} onChange={value => update({...prefs,distance:value})}/><Select label="Budget" disabled={!active} value={prefs.budget} values={['Free only','Free or under $20','Under $50','Any price']} onChange={value => update({...prefs,budget:value})}/><Select label="Group size" disabled={!active} value={prefs.groupSize} values={['2 people','2–4 people','5–8 people','Any size']} onChange={value => update({...prefs,groupSize:value})}/><Select label="Best time" disabled={!active} value={prefs.availability} values={['Friday afternoon','Friday evening','Saturday','Sunday']} onChange={value => update({...prefs,availability:value})}/></div><div className="filter-result">12 events match · Within {prefs.distance} · {prefs.availability}</div></article>
      <article className="premium-tool"><ToolHead number="05" icon="▦" title="Crew planner" text="Replace long group chats with quick date and venue voting."/><Poll title="DATE VOTE" values={prefs.dateVotes} disabled={!active} onVote={choice => vote('dateVotes', choice)}/><Poll title="VENUE VOTE" values={prefs.venueVotes} disabled={!active} onVote={choice => vote('venueVotes', choice)}/></article>
      <article className="premium-tool"><ToolHead number="06" icon="↻" title="Private & recurring crews" text="Create invitation-only groups and plans that repeat automatically."/><Toggle label="Private invitation-only crew" checked={prefs.privateCrew} disabled={!active} onChange={() => update({...prefs,privateCrew:!prefs.privateCrew})}/><Toggle label="Repeat every Sunday at 9:00 AM" checked={prefs.recurring} disabled={!active} onChange={() => update({...prefs,recurring:!prefs.recurring})}/><div className="mini-crew"><span>🌿</span><p><b>Sunday Walk Crew</b><small>{prefs.recurring ? 'Repeats weekly · 5 members' : 'One-time plan · 5 members'}</small></p></div></article>
      <article className="premium-tool"><ToolHead number="07" icon="＋" title="Extra Quest opportunities" text="Get one extra daily claim, one extra active slot and two refreshes."/><div className="benefit-counts"><span><b>4</b> daily claims</span><span><b>3</b> active slots</span><span><b>{refreshes}</b> refreshes</span></div><button className="tool-action" disabled={!active || refreshes === 0} onClick={() => { setRefreshes(value => value - 1); setSaved('Quest Board refreshed with a new recommendation.'); }}>Use a Quest refresh</button></article>
      <article className="premium-tool"><ToolHead number="08" icon="✦" title="Advanced recommendations" text="See why a plan works before sending invitations."/><ul className="recommend-list"><li>All three friends are available</li><li>12 minutes from campus</li><li>Under your $20 budget</li><li>Matches previous food quests</li></ul><button className="tool-action" disabled={!active} onClick={() => setSaved('Recommended Food Trail saved to your Quest Board.')}>Save recommended plan</button></article>
      <article className="premium-tool"><ToolHead number="09" icon="↗" title="Reconnect suggestions" text="Turn good past connections into another real plan."/><div className="reconnect-card"><span>🌻</span><p><small>3 WEEKS SINCE YOUR LAST QUEST</small><b>Reconnect with Maya</b><span>Suggested: Coffee Catch-up this Friday</span></p></div><button className="tool-action" disabled={!active} onClick={() => setSaved('A Coffee Catch-up invitation draft was created for Maya.')}>Create reconnect Quest</button></article>
      <article className="premium-tool wide"><ToolHead number="10" icon="↗" title="Private social insights" text="Understand your activity patterns—never a public popularity score."/><div className="insight-grid"><span><b>6</b> quests completed</span><span><b>4</b> friends met</span><span><b>3</b> new venues</span><span><b>3 weeks</b> longest streak</span></div><p className="insight-tip">✦ You complete more plans on Friday afternoons. Try scheduling your next Crew Quest then.</p></article>
      <article className="premium-tool"><ToolHead number="11" icon="⚡" title="Early access & alerts" text="Preview limited Quest drops and get useful availability alerts."/><Toggle label="15-minute early Quest preview" checked={prefs.earlyAccess} disabled={!active} onChange={() => update({...prefs,earlyAccess:!prefs.earlyAccess})}/><div className="early-drop"><small>NEXT PREMIUM DROP</small><b>Weekend Food Trail</b><span>Tomorrow · 8:00 AM · 10 spots</span></div></article>
      <article className="premium-tool"><ToolHead number="12" icon="⌁" title="Safety & travel convenience" text="Make public meetup planning easier while core safety remains free."/><Toggle label="Prepare trusted-contact plan summary" checked={prefs.trustedContact} disabled={!active} onChange={() => update({...prefs,trustedContact:!prefs.trustedContact})}/><div className="travel-plan"><span>🚌</span><p><b>Best public transport route</b><small>22 min · well-lit arrival point · public venue</small></p></div><button className="tool-action" disabled={!active} onClick={() => setSaved('A private plan summary is ready. Nothing has been shared.')}>Prepare plan summary</button></article>
    </div>
    {!active && <div className="premium-lock"><span>✦</span><div><b>Unlock all 12 planning tools</b><p>Complete social Quests, redeem a Premium pass and activate it when you are ready to plan.</p></div><button onClick={onGetPremium}>View Premium passes →</button></div>}
  </div>;
}

function ToolHead({ number, icon, title, text }: { number: string; icon: string; title: string; text: string }) { return <header className="tool-head"><span>{icon}</span><div><small>{number}</small><h3>{title}</h3><p>{text}</p></div></header>; }
function Toggle({ label, checked, disabled, onChange }: { label: string; checked: boolean; disabled: boolean; onChange: () => void }) { return <button className={`premium-toggle ${checked ? 'on' : ''}`} disabled={disabled} onClick={onChange}><span><i />{label}</span><b>{checked ? 'ON' : 'OFF'}</b></button>; }
function Select({label,disabled,value,values,onChange}:{label:string;disabled:boolean;value:string;values:string[];onChange:(value:string)=>void}) { return <label>{label}<select disabled={disabled} value={value} onChange={event => onChange(event.target.value)}>{values.map(item => <option key={item}>{item}</option>)}</select></label>; }
function Poll({ title, values, disabled, onVote }: { title: string; values: Record<string, number>; disabled: boolean; onVote: (choice: string) => void }) { const max = Math.max(...Object.values(values)); return <div className="premium-poll"><small>{title}</small>{Object.entries(values).map(([choice,votes]) => <button disabled={disabled} key={choice} onClick={() => onVote(choice)}><span>{choice}</span><i><u style={{width:`${(votes / (max + 1)) * 100}%`}} /></i><b>{votes}</b></button>)}</div>; }
